name: action
on: 
  push:
    branches: 
      - main 
jobs:
  build-and-deploy:
      runs-on: self-hosted
      steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: test 
        run: echo Hello